// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBXoEvWNuVsgvJzixwYg0s9BSITMZZYAc',
    appId: '1:833441979479:web:018c8b2575ead1567ed712',
    messagingSenderId: '833441979479',
    projectId: 'ecommerceapp-93686',
    authDomain: 'ecommerceapp-93686.firebaseapp.com',
    databaseURL: 'https://ecommerceapp-93686-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerceapp-93686.appspot.com',
    measurementId: 'G-MNG7LH9LT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAobwTumpANCY2EN_sfLO5MhRzA2Xi7jQs',
    appId: '1:833441979479:android:9f2b3b5a2ee826df7ed712',
    messagingSenderId: '833441979479',
    projectId: 'ecommerceapp-93686',
    databaseURL: 'https://ecommerceapp-93686-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerceapp-93686.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACsGjSdjXsmLBrJ1ndA3HH-nGg5H6TLHY',
    appId: '1:833441979479:ios:7f2e3e6808d9fcbd7ed712',
    messagingSenderId: '833441979479',
    projectId: 'ecommerceapp-93686',
    databaseURL: 'https://ecommerceapp-93686-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerceapp-93686.appspot.com',
    iosClientId: '833441979479-hhk4kh5pmgu0eekdfb1rmc0pljhhln8n.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
